"""
Create and verify BIMAP report-artifact manifests.

This module is the reporting-layer adapter around the authoritative external
``ReportArtifactContract`` and ``ReportManifest`` contracts. It computes
artifact integrity metadata from the actual generated bytes, constructs a
versioned report manifest, and verifies that a manifest still matches the
artifact set before packaging or publication.

It does not render reports, write files to storage, choose customer-retention
policy, or define another manifest schema. Those responsibilities remain with
``report_builder.py``, application/infrastructure services, and
``contracts/report_manifest.py`` respectively.
"""

from __future__ import annotations

import hashlib

from collections.abc import Mapping
from typing import Any

from ..contracts.utils.contracts_errors import ContractError
from .utils.reporting_errors import *
from .utils.reporting_helpers import announce_reporting_action
from ..contracts.report_manifest import *
from logs.logger import PrettyPrinter, get_logger  # type: ignore


logger = get_logger("BIMAP Reporting Artifact Manifest")
printer = PrettyPrinter()

_COMPONENT = "artifact_manifest"
_BYTES_TYPES = (bytes, bytearray, memoryview)


def _as_bytes(value: Any, *, field: str) -> bytes:
    """Normalize one artifact payload without adding a second data model."""
    announce_reporting_action(
        printer,
        logger,
        component=_COMPONENT,
        action="Normalizing generated artifact bytes",
        event="artifact_manifest_bytes_normalize_start",
        context={"field": field, "received_type": type(value).__name__},
    )

    if not isinstance(value, _BYTES_TYPES):
        raise ReportingValidationError(
            "Generated report artifacts must be bytes-like values.",
            component=_COMPONENT,
            field=field,
            context={"received_type": type(value).__name__},
        )
    return bytes(value)


class ArtifactManifest:
    """
    Build and verify immutable report-package manifest metadata.

    ``ReportManifest`` remains the authoritative external schema. This class
    only derives artifact hash/size records from generated bytes and validates
    the relationship between the contract and those bytes.
    """

    def __init__(self, *, sort_artifacts: bool = True) -> None:
        announce_reporting_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Initializing artifact manifest service",
            event="artifact_manifest_init",
            context={"sort_artifacts": sort_artifacts},
        )
        self.sort_artifacts = bool(sort_artifacts)
        logger.info({"event": "artifact_manifest_initialized"})

    def build_artifact_contracts(
        self,
        artifacts: Mapping[str, bytes | bytearray | memoryview],
        *,
        artifact_ids: Mapping[str, str],
    ) -> tuple[ReportArtifactContract, ...]:
        """
        Derive immutable artifact contracts from the generated artifact bytes.

        ``artifact_ids`` is caller-supplied deliberately. BIMAP's source
        material requires stable artifact identity but does not define an ID
        generation format, so the reporting layer must not invent one.
        """
        announce_reporting_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Building report artifact contracts",
            event="artifact_manifest_build_records_start",
            context={"artifact_count": len(artifacts) if isinstance(artifacts, Mapping) else None},
        )

        if not isinstance(artifacts, Mapping):
            raise ReportingValidationError(
                "artifacts must be a mapping of filename to bytes.",
                component=_COMPONENT,
                field="artifacts",
                context={"received_type": type(artifacts).__name__},
            )
        if not isinstance(artifact_ids, Mapping):
            raise ReportingValidationError(
                "artifact_ids must be a mapping of filename to stable artifact ID.",
                component=_COMPONENT,
                field="artifact_ids",
                context={"received_type": type(artifact_ids).__name__},
            )
        if not artifacts:
            raise ArtifactManifestError(
                "At least one generated artifact is required to create a report manifest.",
                component=_COMPONENT,
                field="artifacts",
            )

        artifact_keys = set(artifacts)
        id_keys = set(artifact_ids)
        if artifact_keys != id_keys:
            raise ArtifactManifestError(
                "artifact_ids must identify exactly the generated artifact set.",
                component=_COMPONENT,
                field="artifact_ids",
                context={
                    "missing_ids_for": tuple(sorted(artifact_keys - id_keys)),
                    "unexpected_ids_for": tuple(sorted(id_keys - artifact_keys)),
                },
            )

        records: list[ReportArtifactContract] = []
        normalized_filenames: set[str] = set()
        normalized_ids: set[str] = set()

        try:
            names = sorted(artifacts) if self.sort_artifacts else list(artifacts)
            for index, filename in enumerate(names):
                if not isinstance(filename, str):
                    raise ReportingValidationError(
                        "Artifact filename keys must be strings.",
                        component=_COMPONENT,
                        field=f"artifacts[{index}]",
                        context={"received_type": type(filename).__name__},
                    )

                data = _as_bytes(artifacts[filename], field=f"artifacts[{filename!r}]")
                artifact_id = artifact_ids[filename]

                record = ReportArtifactContract(
                    artifact_id=artifact_id,
                    filename=filename,
                    sha256=hashlib.sha256(data).hexdigest(),
                    size_bytes=len(data),
                )

                if record.filename in normalized_filenames:
                    raise ArtifactManifestError(
                        "Generated artifacts normalize to duplicate filenames.",
                        component=_COMPONENT,
                        field="artifacts",
                        context={"filename": record.filename},
                    )
                if record.artifact_id in normalized_ids:
                    raise ArtifactManifestError(
                        "Generated artifacts contain duplicate artifact identifiers.",
                        component=_COMPONENT,
                        field="artifact_ids",
                        context={"artifact_id": record.artifact_id},
                    )

                normalized_filenames.add(record.filename)
                normalized_ids.add(record.artifact_id)
                records.append(record)

            result = tuple(records)
            logger.debug(
                {
                    "event": "artifact_manifest_records_built",
                    "artifact_count": len(result),
                }
            )
            return result
        except ReportingError:
            raise
        except ContractError as exc:
            raise ArtifactManifestError(
                "Generated artifact metadata violates the report-manifest contract.",
                component=_COMPONENT,
                cause=exc,
            ) from exc
        except (TypeError, ValueError) as exc:
            raise ArtifactManifestError(
                "Unable to derive report artifact metadata.",
                component=_COMPONENT,
                cause=exc,
            ) from exc

    def create_manifest(
        self,
        *,
        report_id: str,
        order_id: str,
        report_version: str,
        generated_at: Any,
        artifacts: Mapping[str, bytes | bytearray | memoryview],
        artifact_ids: Mapping[str, str],
        finding_refs: tuple[str, ...] | list[str] = (),
        requirement_refs: tuple[str, ...] | list[str] = (),
        evidence_refs: tuple[str, ...] | list[str] = (),
        contract_versions: Mapping[str, str] | None = None,
        software_versions: Mapping[str, str] | None = None,
        ruleset_versions: Mapping[str, str] | None = None,
        expires_at: Any | None = None,
    ) -> ReportManifest:
        """Construct the authoritative versioned ``ReportManifest`` contract."""
        announce_reporting_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Creating report manifest",
            event="artifact_manifest_create_start",
            context={"report_id": report_id, "order_id": order_id},
        )

        try:
            artifact_records = self.build_artifact_contracts(
                artifacts,
                artifact_ids=artifact_ids,
            )
            manifest = ReportManifest(
                report_id=report_id,
                order_id=order_id,
                report_version=report_version,
                generated_at=generated_at,
                expires_at=expires_at,
                artifacts=artifact_records,
                finding_refs=tuple(finding_refs),
                requirement_refs=tuple(requirement_refs),
                evidence_refs=tuple(evidence_refs),
                contract_versions=dict(contract_versions or {}),
                software_versions=dict(software_versions or {}),
                ruleset_versions=dict(ruleset_versions or {}),
            )
            logger.info(
                {
                    "event": "report_manifest_created",
                    "report_id": manifest.report_id,
                    "order_id": manifest.order_id,
                    "artifact_count": len(manifest.artifacts),
                }
            )
            return manifest
        except ReportingError:
            raise
        except ContractError as exc:
            raise ReportManifestValidationError(
                "Report manifest could not be created from the generated artifacts.",
                component=_COMPONENT,
                cause=exc,
            ) from exc
        except (TypeError, ValueError) as exc:
            raise ArtifactManifestError(
                "Report manifest creation failed.",
                component=_COMPONENT,
                cause=exc,
            ) from exc

    def verify(
        self,
        manifest: ReportManifest,
        artifacts: Mapping[str, bytes | bytearray | memoryview],
    ) -> None:
        """Verify exact artifact membership, byte size, and SHA-256 integrity."""
        announce_reporting_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Verifying report artifact manifest",
            event="artifact_manifest_verify_start",
            context={"report_id": getattr(manifest, "report_id", None)},
        )

        if not isinstance(manifest, ReportManifest):
            raise ReportManifestValidationError(
                "manifest must be a ReportManifest instance.",
                component=_COMPONENT,
                field="manifest",
                context={"received_type": type(manifest).__name__},
            )
        if not isinstance(artifacts, Mapping):
            raise ReportingValidationError(
                "artifacts must be a mapping of filename to bytes.",
                component=_COMPONENT,
                field="artifacts",
                context={"received_type": type(artifacts).__name__},
            )

        expected_names = {record.filename for record in manifest.artifacts}
        actual_names = set(artifacts)
        if expected_names != actual_names:
            raise ArtifactManifestError(
                "Generated artifact set does not match the report manifest.",
                component=_COMPONENT,
                field="artifacts",
                context={
                    "missing": tuple(sorted(expected_names - actual_names)),
                    "unexpected": tuple(sorted(actual_names - expected_names)),
                },
            )

        try:
            for record in manifest.artifacts:
                data = _as_bytes(
                    artifacts[record.filename],
                    field=f"artifacts[{record.filename!r}]",
                )
                actual_size = len(data)
                if actual_size != record.size_bytes:
                    raise ArtifactManifestError(
                        "Generated artifact byte size does not match its manifest record.",
                        component=_COMPONENT,
                        field="size_bytes",
                        context={
                            "artifact_id": record.artifact_id,
                            "expected": record.size_bytes,
                            "actual": actual_size,
                        },
                    )

                digest = hashlib.sha256(data).hexdigest()
                if digest != record.sha256:
                    raise ArtifactManifestError(
                        "Generated artifact content hash does not match its manifest record.",
                        component=_COMPONENT,
                        field="sha256",
                        context={"artifact_id": record.artifact_id},
                    )

            logger.info(
                {
                    "event": "report_manifest_verified",
                    "report_id": manifest.report_id,
                    "artifact_count": len(manifest.artifacts),
                }
            )
        except ReportingError:
            raise
        except (KeyError, TypeError, ValueError) as exc:
            raise ArtifactManifestError(
                "Report artifact verification failed.",
                component=_COMPONENT,
                cause=exc,
            ) from exc

    def serialize(self, manifest: ReportManifest, *, pretty: bool = True) -> str:
        """Serialize an already validated manifest using its canonical contract."""
        announce_reporting_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Serializing report manifest JSON",
            event="artifact_manifest_serialize_start",
            context={"pretty": pretty},
        )

        if not isinstance(manifest, ReportManifest):
            raise ReportManifestValidationError(
                "manifest must be a ReportManifest instance.",
                component=_COMPONENT,
                field="manifest",
                context={"received_type": type(manifest).__name__},
            )
        try:
            return manifest.to_json(pretty=pretty)
        except ContractError as exc:
            raise ReportManifestValidationError(
                "Report manifest JSON serialization failed.",
                component=_COMPONENT,
                cause=exc,
            ) from exc


__all__ = ["ArtifactManifest"]


if __name__ == "__main__":
    print("\n=== Running Artifact Manifest Self-Test ===\n")
    printer.status("TEST", "Artifact Manifest initialized", "info")

    sample_artifacts = {
        "findings.json": b"[]",
        "remediation.csv": b"finding_id\n",
    }
    service = ArtifactManifest()
    manifest = service.create_manifest(
        report_id="REPORT-TEST",
        order_id="ORDER-TEST",
        report_version="1.0",
        generated_at="2026-09-01T00:00:00Z",
        artifacts=sample_artifacts,
        artifact_ids={
            "findings.json": "ART-FINDINGS",
            "remediation.csv": "ART-REMEDIATION",
        },
    )
    service.verify(manifest, sample_artifacts)
    assert ReportManifest.from_json(service.serialize(manifest)) == manifest
    printer.status("PASS", "Artifact manifest create/verify round trip", "success")

    print("\n=== Test ran successfully ===\n")