"""
Operational execution summaries for the BIMAP worker layer.

This module reports on *worker execution*, not on customer audit content.
Customer-facing BIMAP deliverables are generated by ``bimap.reporting`` and are
released through ``JobReport`` / ``FulfilmentService``.  ``WorkerReports``
therefore does not import ``ReportBuilder``, SLAI result mapping, report
serializers, or raw findings/evidence merely to create a second reporting path.

The module provides two deterministic, content-safe views:

* ``WorkerRunSummary`` describes one ``WorkerExecutionResult`` without exposing
  its typed result payload;
* ``WorkerPerformanceReport`` aggregates observed execution counts and elapsed
  durations across a caller-supplied collection of execution results.

No service-level objective, threshold, percentile, success criterion, anomaly
rule, retry decision, or capacity claim is inferred.  Aggregates describe only
the observations supplied by the caller.
"""

from __future__ import annotations

import math

from collections.abc import Iterable, Mapping
from dataclasses import dataclass
from types import MappingProxyType
from typing import Any

from .engine import WorkerExecutionResult, WorkerJobType
from .utils.workers_errors import WorkerIntegrityError, WorkerValidationError
from .utils.workers_helpers import (
    announce_worker_action,
    materialize_worker_iterable,
    optional_worker_text,
    require_worker_text,
)
from logs.logger import PrettyPrinter, get_logger  # type: ignore


logger = get_logger("BIMAP Worker Reports")
printer = PrettyPrinter()

_COMPONENT = "worker_reports"


def _require_non_negative_float(value: Any, *, field: str, operation: str) -> float:
    """Validate an observed non-negative finite numeric statistic."""
    announce_worker_action(
        printer,
        logger,
        component=_COMPONENT,
        action=f"Validating worker report numeric field: {field}",
        event="worker_reports_numeric_validate_start",
        context={"field": field, "operation": operation},
    )
    if isinstance(value, bool) or not isinstance(value, (int, float)):
        raise WorkerValidationError(
            "Worker report numeric field must be numeric.",
            component=_COMPONENT,
            operation=operation,
            field=field,
            context={"received_type": type(value).__name__},
        )
    normalized = float(value)
    if not math.isfinite(normalized) or normalized < 0.0:
        raise WorkerValidationError(
            "Worker report numeric field must be finite and non-negative.",
            component=_COMPONENT,
            operation=operation,
            field=field,
            context={"received": normalized},
        )
    return normalized


def _require_non_negative_int(value: Any, *, field: str, operation: str) -> int:
    """Validate an observed non-negative integer statistic."""
    announce_worker_action(
        printer,
        logger,
        component=_COMPONENT,
        action=f"Validating worker report integer field: {field}",
        event="worker_reports_integer_validate_start",
        context={"field": field, "operation": operation},
    )
    if isinstance(value, bool) or not isinstance(value, int) or value < 0:
        raise WorkerValidationError(
            "Worker report count must be a non-negative integer.",
            component=_COMPONENT,
            operation=operation,
            field=field,
            context={
                "received_type": type(value).__name__,
                "received": value if isinstance(value, int) and not isinstance(value, bool) else None,
            },
        )
    return value


@dataclass(frozen=True, slots=True)
class WorkerRunSummary:
    """Content-safe summary of one completed worker execution."""

    job_type: WorkerJobType | str
    operation: str
    succeeded: bool
    duration_ms: float
    job_id: str | None = None
    result_type: str | None = None
    error_code: str | None = None
    retryable: bool = False

    def __post_init__(self) -> None:
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Validating worker run summary",
            event="worker_reports_run_summary_validate_start",
            context={"job_type": str(self.job_type), "job_id": self.job_id},
        )

        job_type = WorkerJobType.parse(self.job_type)
        operation = require_worker_text(
            self.operation,
            field="operation",
            component=_COMPONENT,
            operation="validate_run_summary",
            max_length=128,
        )
        job_id = optional_worker_text(
            self.job_id,
            field="job_id",
            component=_COMPONENT,
            operation="validate_run_summary",
            max_length=512,
        )
        result_type = optional_worker_text(
            self.result_type,
            field="result_type",
            component=_COMPONENT,
            operation="validate_run_summary",
            max_length=256,
        )
        error_code = optional_worker_text(
            self.error_code,
            field="error_code",
            component=_COMPONENT,
            operation="validate_run_summary",
            max_length=256,
        )
        duration_ms = _require_non_negative_float(
            self.duration_ms,
            field="duration_ms",
            operation="validate_run_summary",
        )

        if not isinstance(self.succeeded, bool):
            raise WorkerValidationError(
                "succeeded must be boolean.",
                component=_COMPONENT,
                operation="validate_run_summary",
                field="succeeded",
                context={"received_type": type(self.succeeded).__name__},
            )
        if not isinstance(self.retryable, bool):
            raise WorkerValidationError(
                "retryable must be boolean.",
                component=_COMPONENT,
                operation="validate_run_summary",
                field="retryable",
                context={"received_type": type(self.retryable).__name__},
            )

        if self.succeeded:
            if error_code is not None or self.retryable:
                raise WorkerIntegrityError(
                    "Successful worker run summary cannot contain failure metadata.",
                    component=_COMPONENT,
                    operation="validate_run_summary",
                    field="error_code",
                    job_type=job_type.value,
                    job_id=job_id,
                )
        else:
            if error_code is None:
                raise WorkerIntegrityError(
                    "Failed worker run summary requires an error code.",
                    component=_COMPONENT,
                    operation="validate_run_summary",
                    field="error_code",
                    job_type=job_type.value,
                    job_id=job_id,
                )
            if result_type is not None:
                raise WorkerIntegrityError(
                    "Failed worker run summary cannot expose a successful result type.",
                    component=_COMPONENT,
                    operation="validate_run_summary",
                    field="result_type",
                    job_type=job_type.value,
                    job_id=job_id,
                )

        object.__setattr__(self, "job_type", job_type)
        object.__setattr__(self, "operation", operation)
        object.__setattr__(self, "job_id", job_id)
        object.__setattr__(self, "result_type", result_type)
        object.__setattr__(self, "error_code", error_code)
        object.__setattr__(self, "duration_ms", duration_ms)

    def to_dict(self) -> dict[str, Any]:
        """Return deterministic JSON-ready operational metadata."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Serializing worker run summary",
            event="worker_reports_run_summary_to_dict_start",
            context={"job_type": self.job_type.value, "job_id": self.job_id},
        )
        return {
            "job_type": self.job_type.value,
            "operation": self.operation,
            "job_id": self.job_id,
            "succeeded": self.succeeded,
            "duration_ms": self.duration_ms,
            "result_type": self.result_type,
            "error_code": self.error_code,
            "retryable": self.retryable,
        }


@dataclass(frozen=True, slots=True)
class WorkerPerformanceReport:
    """Descriptive aggregate over an explicit collection of worker executions."""

    run_count: int
    success_count: int
    failure_count: int
    retryable_failure_count: int
    total_duration_ms: float
    mean_duration_ms: float
    max_duration_ms: float
    by_job_type: Mapping[str, Mapping[str, int]]

    def __post_init__(self) -> None:
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Validating worker performance report",
            event="worker_reports_performance_validate_start",
            context={"run_count": self.run_count},
        )

        run_count = _require_non_negative_int(
            self.run_count,
            field="run_count",
            operation="validate_performance_report",
        )
        success_count = _require_non_negative_int(
            self.success_count,
            field="success_count",
            operation="validate_performance_report",
        )
        failure_count = _require_non_negative_int(
            self.failure_count,
            field="failure_count",
            operation="validate_performance_report",
        )
        retryable_failure_count = _require_non_negative_int(
            self.retryable_failure_count,
            field="retryable_failure_count",
            operation="validate_performance_report",
        )
        total_duration_ms = _require_non_negative_float(
            self.total_duration_ms,
            field="total_duration_ms",
            operation="validate_performance_report",
        )
        mean_duration_ms = _require_non_negative_float(
            self.mean_duration_ms,
            field="mean_duration_ms",
            operation="validate_performance_report",
        )
        max_duration_ms = _require_non_negative_float(
            self.max_duration_ms,
            field="max_duration_ms",
            operation="validate_performance_report",
        )

        if success_count + failure_count != run_count:
            raise WorkerIntegrityError(
                "Worker performance counts are internally inconsistent.",
                component=_COMPONENT,
                operation="validate_performance_report",
                field="run_count",
                context={
                    "run_count": run_count,
                    "success_count": success_count,
                    "failure_count": failure_count,
                },
            )
        if retryable_failure_count > failure_count:
            raise WorkerIntegrityError(
                "Retryable failure count cannot exceed failure count.",
                component=_COMPONENT,
                operation="validate_performance_report",
                field="retryable_failure_count",
            )
        if run_count == 0:
            if any((total_duration_ms, mean_duration_ms, max_duration_ms)):
                raise WorkerIntegrityError(
                    "Empty worker performance report must contain zero durations.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field="duration_ms",
                )
        else:
            expected_mean = total_duration_ms / run_count
            if not math.isclose(mean_duration_ms, expected_mean, rel_tol=1e-12, abs_tol=1e-9):
                raise WorkerIntegrityError(
                    "Worker performance mean duration is inconsistent with total duration.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field="mean_duration_ms",
                    context={
                        "expected": expected_mean,
                        "received": mean_duration_ms,
                    },
                )
            if max_duration_ms > total_duration_ms + 1e-9:
                raise WorkerIntegrityError(
                    "Maximum duration cannot exceed total observed duration.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field="max_duration_ms",
                )

        if not isinstance(self.by_job_type, Mapping):
            raise WorkerValidationError(
                "by_job_type must be a mapping.",
                component=_COMPONENT,
                operation="validate_performance_report",
                field="by_job_type",
                context={"received_type": type(self.by_job_type).__name__},
            )

        normalized_breakdown: dict[str, Mapping[str, int]] = {}
        aggregate_runs = 0
        aggregate_successes = 0
        aggregate_failures = 0
        aggregate_retryable = 0

        for raw_job_type, raw_counts in self.by_job_type.items():
            job_type = WorkerJobType.parse(raw_job_type).value
            if job_type in normalized_breakdown:
                raise WorkerIntegrityError(
                    "by_job_type contains duplicate normalized worker job types.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field="by_job_type",
                    context={"job_type": job_type},
                )
            if not isinstance(raw_counts, Mapping):
                raise WorkerValidationError(
                    "Worker job-type breakdown values must be mappings.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field=f"by_job_type.{job_type}",
                    context={"received_type": type(raw_counts).__name__},
                )

            expected_keys = {"runs", "successes", "failures", "retryable_failures"}
            if set(raw_counts) != expected_keys:
                raise WorkerIntegrityError(
                    "Worker job-type breakdown contains an invalid field set.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field=f"by_job_type.{job_type}",
                    context={
                        "expected_keys": tuple(sorted(expected_keys)),
                        "received_keys": tuple(sorted(str(k) for k in raw_counts)),
                    },
                )

            runs = _require_non_negative_int(
                raw_counts["runs"],
                field=f"by_job_type.{job_type}.runs",
                operation="validate_performance_report",
            )
            successes = _require_non_negative_int(
                raw_counts["successes"],
                field=f"by_job_type.{job_type}.successes",
                operation="validate_performance_report",
            )
            failures = _require_non_negative_int(
                raw_counts["failures"],
                field=f"by_job_type.{job_type}.failures",
                operation="validate_performance_report",
            )
            retryable_failures = _require_non_negative_int(
                raw_counts["retryable_failures"],
                field=f"by_job_type.{job_type}.retryable_failures",
                operation="validate_performance_report",
            )
            if successes + failures != runs or retryable_failures > failures:
                raise WorkerIntegrityError(
                    "Worker job-type breakdown counts are internally inconsistent.",
                    component=_COMPONENT,
                    operation="validate_performance_report",
                    field=f"by_job_type.{job_type}",
                )

            normalized_counts = MappingProxyType(
                {
                    "runs": runs,
                    "successes": successes,
                    "failures": failures,
                    "retryable_failures": retryable_failures,
                }
            )
            normalized_breakdown[job_type] = normalized_counts
            aggregate_runs += runs
            aggregate_successes += successes
            aggregate_failures += failures
            aggregate_retryable += retryable_failures

        if (
            aggregate_runs != run_count
            or aggregate_successes != success_count
            or aggregate_failures != failure_count
            or aggregate_retryable != retryable_failure_count
        ):
            raise WorkerIntegrityError(
                "Worker job-type breakdown does not reconcile with aggregate counts.",
                component=_COMPONENT,
                operation="validate_performance_report",
                field="by_job_type",
            )

        object.__setattr__(self, "run_count", run_count)
        object.__setattr__(self, "success_count", success_count)
        object.__setattr__(self, "failure_count", failure_count)
        object.__setattr__(self, "retryable_failure_count", retryable_failure_count)
        object.__setattr__(self, "total_duration_ms", total_duration_ms)
        object.__setattr__(self, "mean_duration_ms", mean_duration_ms)
        object.__setattr__(self, "max_duration_ms", max_duration_ms)
        object.__setattr__(self, "by_job_type", MappingProxyType(normalized_breakdown))

    def to_dict(self) -> dict[str, Any]:
        """Return deterministic JSON-ready descriptive execution statistics."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Serializing worker performance report",
            event="worker_reports_performance_to_dict_start",
            context={"run_count": self.run_count},
        )
        return {
            "run_count": self.run_count,
            "success_count": self.success_count,
            "failure_count": self.failure_count,
            "retryable_failure_count": self.retryable_failure_count,
            "total_duration_ms": self.total_duration_ms,
            "mean_duration_ms": self.mean_duration_ms,
            "max_duration_ms": self.max_duration_ms,
            "by_job_type": {
                job_type: dict(counts)
                for job_type, counts in self.by_job_type.items()
            },
        }


class WorkerReports:
    """Create content-safe operational summaries from worker execution results."""

    __slots__ = ()

    def __init__(self) -> None:
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Initializing worker execution reports",
            event="worker_reports_init_start",
        )
        logger.info({"event": "worker_reports_initialized"})

    def summarize(self, execution: WorkerExecutionResult[Any]) -> WorkerRunSummary:
        """Summarize one worker execution without serializing its result payload."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Summarizing worker execution",
            event="worker_reports_summarize_start",
            context={"received_type": type(execution).__name__},
        )
        if not isinstance(execution, WorkerExecutionResult):
            raise WorkerValidationError(
                "execution must be a WorkerExecutionResult.",
                component=_COMPONENT,
                operation="summarize",
                field="execution",
                context={"received_type": type(execution).__name__},
            )

        summary = WorkerRunSummary(
            job_type=execution.job_type,
            operation=execution.operation,
            job_id=execution.job_id,
            succeeded=execution.succeeded,
            duration_ms=execution.duration_ms,
            result_type=execution.result_type,
            error_code=execution.error_code,
            retryable=execution.retryable,
        )
        logger.debug(
            {
                "event": "worker_execution_summarized",
                "job_type": summary.job_type.value,
                "job_id": summary.job_id,
                "succeeded": summary.succeeded,
                "duration_ms": summary.duration_ms,
            }
        )
        return summary

    def summarizer(self, execution: WorkerExecutionResult[Any]) -> WorkerRunSummary:
        """Compatibility spelling for :meth:`summarize`."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Summarizing worker execution through compatibility entry",
            event="worker_reports_summarizer_start",
        )
        return self.summarize(execution)

    def execute(self, execution: WorkerExecutionResult[Any]) -> WorkerRunSummary:
        """Execute the worker operational-summary projection for one result."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Executing worker summary projection",
            event="worker_reports_execute_start",
        )
        return self.summarize(execution)

    def performance_report(
        self,
        executions: Iterable[WorkerExecutionResult[Any]],
    ) -> WorkerPerformanceReport:
        """Aggregate descriptive counts and elapsed durations over executions."""
        announce_worker_action(
            printer,
            logger,
            component=_COMPONENT,
            action="Building worker performance report",
            event="worker_reports_performance_start",
        )

        records = materialize_worker_iterable(
            executions,
            field="executions",
            component=_COMPONENT,
            operation="performance_report",
            accepted_type=WorkerExecutionResult,
            allow_empty=True,
        )

        run_count = len(records)
        success_count = sum(1 for item in records if item.succeeded)
        failure_count = run_count - success_count
        retryable_failure_count = sum(
            1 for item in records if item.failed and item.retryable
        )
        total_duration_ms = sum(item.duration_ms for item in records)
        mean_duration_ms = (
            total_duration_ms / run_count if run_count else 0.0
        )
        max_duration_ms = max((item.duration_ms for item in records), default=0.0)

        by_job_type: dict[str, dict[str, int]] = {}
        for job_type in WorkerJobType:
            scoped = tuple(item for item in records if item.job_type is job_type)
            if not scoped:
                continue
            scoped_successes = sum(1 for item in scoped if item.succeeded)
            scoped_failures = len(scoped) - scoped_successes
            by_job_type[job_type.value] = {
                "runs": len(scoped),
                "successes": scoped_successes,
                "failures": scoped_failures,
                "retryable_failures": sum(
                    1 for item in scoped if item.failed and item.retryable
                ),
            }

        report = WorkerPerformanceReport(
            run_count=run_count,
            success_count=success_count,
            failure_count=failure_count,
            retryable_failure_count=retryable_failure_count,
            total_duration_ms=total_duration_ms,
            mean_duration_ms=mean_duration_ms,
            max_duration_ms=max_duration_ms,
            by_job_type=by_job_type,
        )
        logger.info(
            {
                "event": "worker_performance_report_built",
                "run_count": report.run_count,
                "success_count": report.success_count,
                "failure_count": report.failure_count,
                "retryable_failure_count": report.retryable_failure_count,
                "total_duration_ms": report.total_duration_ms,
            }
        )
        return report


__all__ = [
    "WorkerRunSummary",
    "WorkerPerformanceReport",
    "WorkerReports",
]


if __name__ == "__main__":
    from .engine import WorkerEngine

    print("\n=== Running Worker Reports Self-Test ===\n")
    printer.status("TEST", "Worker reports module initialized", "info")

    engine = WorkerEngine()
    reports = WorkerReports()
    first = engine.execute(WorkerJobType.AUDIT, "self_test", lambda: 1)
    second = engine.execute(WorkerJobType.REPORT, "self_test", lambda: None)

    summary = reports.execute(first)
    assert summary.succeeded is True
    aggregate = reports.performance_report((first, second))
    assert aggregate.run_count == 2
    assert aggregate.success_count == 2
    assert aggregate.failure_count == 0

    printer.status("PASS", "Worker execution reporting", "success")
    print("\n=== Test ran successfully ===\n")